---
ID: "cfaf8bf6-7ab2-4a3d-8a87-35f64d0d8fd8"
Parent: "4f8af373-7561-4d9b-b38e-6f196338ee63"
Template: "511b6c4f-3a50-4825-b377-f334f3dfc06c"
Path: /sitecore/system/Settings/AnalyticsUpdater/Analytics Updater Settings
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0d827949-a185-4bdb-8086-07ecf23dd416"
      Hint: Last Refresh Date
      Value: 20170201T000000
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160303T102302Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
